accounts/urls.py
# Django
from django.urls import path
# Project
from . import views

app_name="accounts"
urlpatterns = [
    path('signup/', views.UserCreateView.as_view(), name='signup'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('profile/<pk>', views.UserDetailView.as_view(), name='profile'),
]

inventory/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('item.urls')),
    path('accounts/', include('accounts.urls')),
    path('store/', include('store.urls'))
]

item/urls.py
from django.urls import path
from . import views

app_name="item"
urlpatterns = [
    path('', views.ListAndCreate.as_view(), name='index'),
    path('create/', views.ListAndCreate.as_view(), name='create'),
    path('delete-item/<pk>', views.ItemDeleteView.as_view(), name='delete'),
    path('item/<pk>', views.ListAndDetail.as_view(), name='details'),
    path('search/?query=', views.ItemSearchView.as_view(), name='search')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class Employee(AbstractUser):
        has_access=models.BooleanField(default=True)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Employee


class EmployeeCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = Employee
        fields=['first_name','last_name','username','email','password1','password2']


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = Employee
        fields = ['username', 'password']

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView
from .forms import CustomAuthenticationForm,EmployeeCreationForm
from django.contrib.auth.models import User
from .models import Employee
# Create your views here.


class UserCreateView(CreateView):
    form_class=EmployeeCreationForm
    template_name = "accounts/signup.html"
    success_url = reverse_lazy('item:index')


class CustomLoginView(LoginView):
    authentication_form = CustomAuthenticationForm
    template_name = 'accounts/login.html'


class UserDetailView(LoginRequiredMixin,DetailView):
    model = Employee
    template_name = "accounts/profile.html"


class UserLogOutView(LogoutView):
    model = Employee
    template_name = 'accounts/logout.html'

templates/accounts/login.html
{% extends "../base.html" %}
{% load widget_tweaks %}
{% block title %}
  Log in
{% endblock title %}
{% block content %}
<script>
  $('.message a').click(function () {
    $('form').animate({ height: "toggle", opacity: "toggle" }, "slow");
  });
</script>
<div class="login-page">
  <div class="form">
    {% csrf_token %}
    <form class="login-form" action="{%url 'accounts:login'%}" method="post">
      {% csrf_token %}
      <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
        {% for error in form.non_field_errors %}
        <div class="text-danger">
            <p>{{ error }}</p>
        </div>
        {% endfor %}
      </div>
      {% for field in form %}
      <div class="form-group">
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
          <p class="help-block text-danger">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
      {% endfor %}

      <button type="submit">log in</button>
      <p class="message">Not registered? <a href="{%url 'accounts:signup'%}">Create an account</a></p>
    </form>
  </div>
</div>
{% endblock content %}

templates/accounts/logout.html
{% include '../base.html' %}
{% block content %}
  You have been logged out. <a href="{% url 'accounts:login' %}">Log in</a>
{% endblock content %}

templates/accounts/profile.html
{% extends '../store/index.html' %}
{% block list_content %}
<ul>
      <li>Name: {{user.first_name}} {{user.last_name}}</li>
      <li>Username: {{user.username}}</li>
      <li>Email Address: {{user.email}}</li>
</ul>
{% endblock list_content %}

templates/accounts/signup.html
{% extends "../base.html" %}
{% load widget_tweaks %}
{% block title %}
  Sign up
{% endblock title %}
{% block content %}
<div class="main-w3layouts wrapper">
  <script type="application/x-javascript">
    addEventListener("load", 
    function() { 
      setTimeout(hideURLbar, 0);
     },
      false); 
    function hideURLbar(){
       window.scrollTo(0,1);
       } 
  </script>
  <h1>Create Account</h1>
  <div class="main-agileinfo">
    <div class="agileits-top">
      <form action="{%url 'accounts:signup'%}" method="post">
        {% csrf_token %}
        <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
          {% for error in form.non_field_errors %}
          <div class="text-warning">
            {{ error }}
          </div>
          {% endfor %}
        </div>
        {% for field in form %}

        <div class="form-group">
          {% render_field field|attr:"required autofocus" class="form-control" placeholder=field.label %}
          <div class="{% if field.errors %} invalid{% endif %} text-danger">
            {% for error in field.errors %}
            <p class="help-block text-warning">{{ error }}</p>
            {% endfor %}
          </div>
        </div>
        {%endfor%}
        <style>
          button {
            font-family: "Roboto", sans-serif;
            text-transform: uppercase;
            outline: 0;
            background: #4CAF50;
            width: 100%;
            border: 0;
            padding: 15px;
            color: #FFFFFF;
            font-size: 14px;
            -webkit-transition: all 0.3 ease;
            transition: all 0.3 ease;
            cursor: pointer;
          }

          button:hover,
          active,
          button:focus {
            background: #43A047;
          }
        </style>
        <button type="submit">Sign Up</button>
      </form>
      <p>Have an Account? <a href="{%url 'accounts:login'%}"> Login Now!</a></p>
    </div>
  </div>
  <!-- copyright -->
  <div class="colorlibcopy-agile">
    <p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/"
        target="_blank">Colorlib</a></p>
  </div>
  <!-- //copyright -->
  <ul class="colorlib-bubbles">
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
  </ul>
</div>
{%endblock content%}