accounts/urls.py
# Django
from django.urls import path
# Project
from . import views

app_name="accounts"
urlpatterns = [
    path('signup/', views.UserCreateView.as_view(), name='signup'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('profile/<pk>', views.UserDetailView.as_view(), name='profile'),
]

inventory/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('item.urls')),
    path('accounts/', include('accounts.urls')),
    path('store/', include('store.urls'))
]

item/urls.py
from django.urls import path
from . import views

app_name="item"
urlpatterns = [
    path('', views.ListAndCreate.as_view(), name='index'),
    path('create/', views.ListAndCreate.as_view(), name='create'),
    path('delete-item/<pk>', views.ItemDeleteView.as_view(), name='delete'),
    path('item/<pk>', views.ListAndDetail.as_view(), name='details'),
    path('search/?query=', views.ItemSearchView.as_view(), name='search')
]

store/urls.py
from django.urls import path
from . import views

app_name = "store"
urlpatterns = [
    path(
        '',
        views.StoreCreateView.as_view(),
        name='list'),
    path(
        'create/',
        views.StoreCreateView.as_view(),
        name='create'),
    path(
        '<pk>/details/',
        views.StoreDetailView.as_view(),
        name='details'),
    path(
        '<pk>/delete/',
        views.StoreDeleteView.as_view(),
        name='delete'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html class="no-js">
<!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>
        {% block title %}
        Inventory manager
        {% endblock title %}
    </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    {% if not user.is_authenticated %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endif %}


    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

    <script type="application/x-javascript">
        addEventListener("load", function() {
             setTimeout(hideURLbar, 0); }, false); 
             function hideURLbar(){ 
                 window.scrollTo(0,1); }
   </script>
    <style>
        .ui-widget-overlay {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: #aaaaaa;
            opacity: 0.3;
        }

        #loader {
            position: fixed;
            display: none;
            width: 100%;
            height: 100%;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
        }

        .loader {
            position: absolute;
            top: 50%;
            left: 50%;
            font-size: 50px;
            transform: translate(-50%, -50%);
            -ms-transform: translate(-50%, -50%);
        }
    </style>

</head>

<body>
    {% block content %}

    {% endblock content %}
    {% block modal %}

    {% endblock modal %}
    {% block extrascripts %}

    {% endblock extrascripts %}

</body>


</html>

templates/header.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="{%url 'item:index'%}">StoreMan</a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
        aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="{%url 'item:index'%}">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'store:list'%}">
                    <i class="fab fa-container-storage red"></i>
                    Stores
                </a>
            </li>
            <li class="dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">
                    <span class="fa fa-user" aria-hidden="true"></span>
                    {{user.first_name}}
                </a>
                <div class="dropdown-menu bg-dark" aria-labelledby="dropdownId">
                    <a href="{%url 'accounts:profile' pk=user.id %}" class="dropdown-item">
                        Profile
                    </a>
                    <a href="{%url 'accounts:logout' %}" class="dropdown-item">
                        Log out
                    </a>
                </div>
            </li>
            </a>
        </ul>
        <form class="form-inline my-2 my-lg-0" method="GET" id="search-form" data-url="{%url 'item:search'%}"
            action="{%url 'item:search'%}">
            <input class="form-control mr-sm-2" name="query" id="item" type="text" placeholder="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" id="search-btn" type="submit">Search</button>
        </form>
    </div>
</nav>

templates/messages.html
{% for message in messages %}
<div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
</div>
{% endfor %}