accounts/urls.py
# Django
from django.urls import path
# Project
from . import views

app_name="accounts"
urlpatterns = [
    path('signup/', views.UserCreateView.as_view(), name='signup'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('profile/<pk>', views.UserDetailView.as_view(), name='profile'),
]

inventory/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('item.urls')),
    path('accounts/', include('accounts.urls')),
    path('store/', include('store.urls'))
]

item/urls.py
from django.urls import path
from . import views

app_name="item"
urlpatterns = [
    path('', views.ListAndCreate.as_view(), name='index'),
    path('create/', views.ListAndCreate.as_view(), name='create'),
    path('delete-item/<pk>', views.ItemDeleteView.as_view(), name='delete'),
    path('item/<pk>', views.ListAndDetail.as_view(), name='details'),
    path('search/?query=', views.ItemSearchView.as_view(), name='search')
]

store/urls.py
from django.urls import path
from . import views

app_name = "store"
urlpatterns = [
    path(
        '',
        views.StoreCreateView.as_view(),
        name='list'),
    path(
        'create/',
        views.StoreCreateView.as_view(),
        name='create'),
    path(
        '<pk>/details/',
        views.StoreDetailView.as_view(),
        name='details'),
    path(
        '<pk>/delete/',
        views.StoreDeleteView.as_view(),
        name='delete'),
]

store/models.py
from django.db import models
from django.db.models.signals import pre_save
from .utils import unique_store_id_generator
from accounts.models import Employee
# Create your models here.


class Store(models.Model):
    name = models.CharField(max_length=30, unique=True,verbose_name="Store name")
    capacity = models.IntegerField(default=0, verbose_name="Capacity")
    number_of_items = models.IntegerField(default=0)
    manager = models.ForeignKey(
        Employee, on_delete=models.CASCADE, related_name="Manager")
    store_id = models.CharField(max_length=10,
                                primary_key=True, null=False)
    store_users = models.ManyToManyField(Employee)

    def __str__(self):
        return self.name


def pre_save_create_store_id(sender, instance, *args, **kwargs):
    if not instance.store_id:
        instance.store_id = unique_store_id_generator(instance)


pre_save.connect(pre_save_create_store_id, sender=Store)

store/views.py
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.views.generic import (
    CreateView,
    DetailView,
    DeleteView,
    ListView,
    UpdateView)
from django.utils import timezone
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from mixins import AjaxableFormMixin
from .models import Store
from accounts.models import Employee

# Create your views here.


class StoreCreateView(LoginRequiredMixin, CreateView):
    model = Store
    fields = ['name', 'capacity', 'store_users']
    template_name = "store/create.html"
    success_url = reverse_lazy('store:create')

    def form_valid(self, form):
        form.instance.manager = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        employee = Employee.objects.get(username=self.request.user.username)
        context = super(StoreCreateView, self).get_context_data(**kwargs)
        context["object_list"] = self.model.objects.filter(
            store_users=employee)
        return context


class StoreDetailView(LoginRequiredMixin, DetailView):
    model = Store
    template_name = "store/details.html"

    def get_context_data(self, **kwargs):
        employee = Employee.objects.get(username=self.request.user.username)
        context = super(StoreDetailView, self).get_context_data(**kwargs)
        context["object_list"] = self.model.objects.filter(
            store_users=employee)
        return context


class StoreDeleteView(LoginRequiredMixin, AjaxableFormMixin, DeleteView):
    model = Store
    success_url = reverse_lazy('store:list')

templates/store/create.html
{% extends './index.html' %}
{% load widget_tweaks %}
{% load static %}
{% block sidebar %}
<h2 class="mb-4">Add Store</h2>
<form class="create-form" action="{%url 'store:create'%}" data-url="{%url 'store:create'%}" method="post">
    {% csrf_token %}
    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
        {% for error in form.non_field_errors %}
        {{ error }}
        {% endfor %}
    </div>

    {% for field in form %}
    {% if not user.is_superuser %}
    <div class="form-group row">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control"%}
        <div class="{% if field.errors %} invalid{% endif %}">
            {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
            {% endfor %}
        </div>
    </div>
    {% endif %}
    {% endfor %}
    <button type="submit" id="submit-btn" class="btn btn-primary">Add store</button>
</form>
{% endblock sidebar %}
{% block extrascripts %}
<script src="{% static 'js/script.js' %}"></script>
{% endblock extrascripts %}

templates/store/details.html
{% extends "./index.html" %}
{% block sidebar %}
<div class="details">
    <h2 style="text-align: center" class="mb-4">Details of {{store.store_id}}</h2>
    <dl class="row">
        <dt class="col-sm-4">Name:
        <dd class="col-sm-8">
            {{store.name}}
        </dd>
        </dt>
        <dt class="col-sm-4">Capacity:
        <dd class="col-sm-8">
            {{store.capacity}}
        </dd>
        </dt>
        <dt class="col-sm-4">Items in store:
        <dd class="col-sm-8">
            {{store.number_of_items}}
        </dd>
        </dt>
        <dt class="col-sm-4">Store users:
        <dd class="col-sm-8">
            <ul>

                {% for user in store.store_users.values_list.values %}
                <li>{{user.first_name}} {{user.last_name}} <a
                        href="{%url 'accounts:profile' pk=user.id%}">@{{user.username}}</a></li>
                {% endfor %}
            </ul>


        </dd>
        </dt>
    </dl>
    <style>
        button {
            margin: 20px;
        }
    </style>
    <div class="btn-group" role="group" aria-label="Button group">
        <a href="{%url 'store:create'%}">
            <button class="btn btn-primary">
                <span class="fa fa-plus" aria-hidden="true"></span>
                New store
            </button>
        </a>
        <div>
            <form id="item-delete" method="POST" action="{%url 'store:delete' pk=store.store_id%}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">
                    <span class="fa fa-eraser" aria-hidden="true"></span>
                    Remove store
                </button>
            </form>
        </div>
    </div>
    <div class="text-danger">
        <i>
            Removing this store will also remove all the items stored in it.
            <strong>Proceed with caution!</strong>
        </i>
    </div>
</div>
{% endblock sidebar %}

templates/store/index.html
{% extends '../base.html' %}
{% block title %}
Stores
{% endblock title %}
{% block content %}
{% load static %}
{% if user.is_authenticated%}
{% include '../header.html' %}
<div class="container-fluid row">
    <div class="col-sm-8">
        <div id='loader' style='display: none;'>
            <img src='{%static "img/image.gif"%}' class="loader">
        </div>

        {% block list_content %}
        {% include "./store_list.html" %}
        {% endblock list_content %}
    </div>
    <div class="col-sm-4">
        <div id='loader' style='display: none;'>
            <img src='{%static "img/image.gif"%}' class="loader">
        </div>
        {% block sidebar %}
        {% endblock sidebar %}
    </div>
</div>
{%endif%}
{% endblock content %}

templates/store/store_list.html
<script>
    $(document).ready(function () {
        $('#items-table').DataTable();
    });
</script>
<h2 style="text-align: center" class="mb-4">Your stores</h2>

<table id="items-table" class="table table-striped table-bordered" style="width:100%">

    <thead>
        <tr>
            <th>Store ID</th>
            <th>Store name</th>
        </tr>
    </thead>
    <tbody>
        {% for store in object_list %}
        <tr>
            <td scope="row">
                <a class="item btn btn-outline" href="{%url 'store:details' pk=store.store_id%}">
                    {{store.store_id}}
                </a>
            </td>
            <td>{{store.name}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>