inventory/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('item.urls')),
    path('accounts/', include('accounts.urls')),
    path('store/', include('store.urls'))
]

item/urls.py
from django.urls import path
from . import views

app_name="item"
urlpatterns = [
    path('', views.ListAndCreate.as_view(), name='index'),
    path('create/', views.ListAndCreate.as_view(), name='create'),
    path('delete-item/<pk>', views.ItemDeleteView.as_view(), name='delete'),
    path('item/<pk>', views.ListAndDetail.as_view(), name='details'),
    path('search/?query=', views.ItemSearchView.as_view(), name='search')
]

store/urls.py
from django.urls import path
from . import views

app_name = "store"
urlpatterns = [
    path(
        '',
        views.StoreCreateView.as_view(),
        name='list'),
    path(
        'create/',
        views.StoreCreateView.as_view(),
        name='create'),
    path(
        '<pk>/details/',
        views.StoreDetailView.as_view(),
        name='details'),
    path(
        '<pk>/delete/',
        views.StoreDeleteView.as_view(),
        name='delete'),
]

item/models.py
from django.db import models
from django.utils import timezone
from django.db.models.signals import pre_save
from .utils import unique_item_id_generator
from store.models import Store
from accounts.models import Employee
# Create your models here.


class Item(models.Model):

    WEIGHT_CLASSES = [
        ("kg", "Kilograms"),
        ("g", "Grams"),
        ("t", "Tonnes"),
    ]
    ITEM_CLASSES = [
        ("A", "Electronics"),
        ("B", "Chemicals"),
        ("C", "Books"),
        ("D", "Clothing"),
        ("E", "Food"),
        ("F", "Other"),
    ]
    item_store = models.ForeignKey(Store, on_delete=models.CASCADE)
    added_by = models.ForeignKey(Employee, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name="Item name")
    item_num = models.IntegerField(verbose_name="No. of units")
    date_stored = models.DateTimeField(
        verbose_name="Date of entry", default=timezone.now)
    date_removed = models.DateTimeField(null=True)
    fragile = models.BooleanField(verbose_name="Fragile")
    weight = models.DecimalField(
        verbose_name="Weight", decimal_places=2, max_digits=5)
    units = models.CharField(
        max_length=20, verbose_name="Units", choices=WEIGHT_CLASSES, null=False, blank=False)
    item_class = models.CharField(
        max_length=1,
        verbose_name="Item class",
        choices=ITEM_CLASSES,
        default="A")
    item_id = models.CharField(max_length=10, verbose_name="Item ID",
                               primary_key=True, null=False)

    def __str__(self):
        return self.item_id


def pre_save_create_item_id(sender, instance, *args, **kwargs):
    if not instance.item_id:
        instance.item_id = unique_item_id_generator(instance)


pre_save.connect(pre_save_create_item_id, sender=Item)

item/views.py
from mixins import AjaxableFormMixin
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.views.generic import (
    CreateView,
    DetailView,
    DeleteView,
    ListView,
    UpdateView)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.urls import reverse_lazy
from django.db.models import Q

from .models import Item
from accounts.models import Employee
from store.models import Store
# Create your views here.


class ItemUpdateView(LoginRequiredMixin, UpdateView):
    model = Item
    template_name = "item/update_item.html"
    success_url = reverse_lazy('item:index')


class ItemDeleteView(LoginRequiredMixin, DeleteView):
    model = Item
    success_url = reverse_lazy('item:index')


class ListAndCreate(LoginRequiredMixin, AjaxableFormMixin, CreateView):
    model = Item
    fields = [
        "name",
        "item_num",
        "fragile",
        "weight",
        'units',
        "item_class",
        'item_store',
    ]
    template_name = "item/create.html"
    success_url = reverse_lazy('item:index')

    def form_valid(self, form):
        print(form.instance.item_store)
        form.instance.added_by = self.request.user
        store = Store.objects.get(
            name=form.instance.item_store).number_of_items
        Store.objects.filter(name=form.instance.item_store).update(number_of_items=store +
                                                                   form.instance.item_num)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        employee = Employee.objects.get(username=self.request.user.username)
        context = super(ListAndCreate, self).get_context_data(**kwargs)
        context["object_list"] = self.model.objects.filter(added_by=employee)
        return context


class ListAndDetail(LoginRequiredMixin, DetailView):
    model = Item
    template_name = "item/item.html"

    def get_context_data(self, **kwargs):
        employee = Employee.objects.get(username=self.request.user.username)
        context = super(ListAndDetail, self).get_context_data(**kwargs)
        context["object_list"] = self.model.objects.filter(added_by=employee)
        return context


class ItemSearchView(LoginRequiredMixin, ListView):
    model = Item
    template_name = "item/create.html"

    def get_context_data(self, **kwargs):
        query = self.request.GET.get('query')
        employee = Employee.objects.get(username=self.request.user.username)
        context = super(ItemSearchView, self).get_context_data(**kwargs)
        context["object_list"] = self.model.objects.filter(
            Q(added_by=employee) & (Q(name__icontains=query) | Q(item_id__icontains=query)))
        return context

templates/item/create.html
{% extends './index.html' %}
{% load widget_tweaks %}
{% load static %}
{% block sidebar %}
<h2 class="mb-4">Add item</h2>
<form class="create-form" action="{%url 'item:create'%}" data-url="{%url 'item:create'%}" method="post">
    {% csrf_token %}
    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
        {% for error in form.non_field_errors %}
        {{ error }}
        {% endfor %}
    </div>

    {% for field in form %}
    {% if not user.is_superuser %}
    <div class="form-group row">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control"%}
        <div class="{% if field.errors %} invalid{% endif %}">
            {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
            {% endfor %}
        </div>
    </div>
    {% endif %}
    {% endfor %}
    <button type="submit" id="submit-btn" class="btn btn-primary">Add item</button>
</form>
{% endblock sidebar %}
{% block extrascripts %}
<script src="{% static 'js/script.js' %}"></script>
{% endblock extrascripts %}

templates/item/index.html
{% extends '../base.html' %}
{% load static %}
{% block title %}
Items
{% endblock title %}
{% block content %}
{% if user.is_authenticated %}
{% include '../header.html' %}
<div class="container-fluid row">
    <div class="col-sm-8" id="list">

        <div id='loader' style='display: none;'>
            <img src='{%static "img/image.gif"%}' class="loader">
        </div>

        {% block list_content %}
        {% include "item/item_list.html" %}
        {% endblock list_content %}
    </div>
    <div class="col-sm-4" id="item:details">
        <div id='loader' style='display: none;'>
            <img src='{%static "img/image.gif"%}' class="loader">
        </div>

        {% block sidebar %}
        {% endblock sidebar %}
    </div>
</div>
{%endif%}
{% endblock content %}

templates/item/item.html
{% extends "./index.html" %}
{% block sidebar %}
<div class='details'>
    <h2 style="text-align: center" class="mb-4">Details of {{item.item_id}}</h2>
    <dl class="row">
        <dt class="col-sm-4">Name:
        <dd class="col-sm-8">
            {{item.name}}
        </dd>
        </dt>
        <dt class="col-sm-4">Amount in store:
        <dd class="col-sm-8">
            {{item.item_num}}
        </dd>
        </dt>
        <dt class="col-sm-4">Individual weight:
            <dd class="col-sm-8">
                {{item.weight}} {{item.units}}
            </dd>
            </dt>
        <dt class="col-sm-4">Date stored:
        <dd class="col-sm-8">
            {{item.date_stored}}
        </dd>
        </dt>
        <dt class="col-sm-4">Store name:
        <dd class="col-sm-8">
            {{item.item_store}}
            <a class="item" href="{%url 'store:details' pk=item.item_store.store_id%}">
                @{{item.item_store.store_id}}
            </a>
        </dd>
        </dt>
        <dt class="col-sm-4">Added by:
            <dd class="col-sm-8">
                {{item.added_by.first_name}} {{item.added_by.last_name}} 
                <a class="item" href="{%url 'store:details' pk=item.item_store.store_id%}">
                    @{{item.added_by.username}}
                </a>
            </dd>
            </dt>
    </dl>
    <style>
        button {
            margin: 20px;
        }
    </style>
    <div class="btn-group" role="group" aria-label="Button group">
        <a href="{%url 'item:create'%}">
            <button class="btn btn-primary">
                <span class="fa fa-plus" aria-hidden="true"></span>
                New item
            </button>
        </a>
        <div>
            <form method="POST" id="item-delete" action="{%url 'item:delete' pk=item.item_id%}" data-url="{%url 'item:delete' pk=item.item_id%}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger>
                    <span class="fa fa-eraser" aria-hidden="true"></span>
                    Remove item
                </button>
            </form>

        </div>
    </div>
    <div class="text-danger">
        <i>
            Items removed cannot be recovered. 
            <strong>Proceed with caution!</strong>
        </i>
    </div>
</div>
{% endblock sidebar %}

templates/item/item_list.html
<script>
    $(function () {
        $('#items-table').DataTable();
    });
</script>
<h2 style="text-align: center" class="mb-4">Items currently in the inventory</h2>
<div id="div-test">
    <table id="items-table" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Item ID</th>
                <th>Item name</th>
                <th>Units in store</th>
                <th>Item class</th>
            </tr>
        </thead>
        <tbody>
            {% for item in object_list %}
            <tr>
                <td scope="row">
                    <a class="item btn text-danger" data-url="{%url 'item:details' pk=item.item_id%}">
                        {{item.item_id}}
                    </a>
                </td>
                <td>{{item.name}}</td>
                <td>{{item.item_num}}</td>
                <td>{{item.get_item_class_display}}</td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
</div>